### ISSUE TITLE
Could the font size be changed in amsart template?

### ISSUE THREAD

**Issue by i-Faye00** [Jinwen-XU/ProjLib#1]
When I use the documentclass of amsart with the ProjLib package, I noticed the margin would become very small in font size 11pt, and very close to zero in 12pt. 
Is there any solution for this issue? Thank you so much!

**Comment by Jinwen-XU** [comment]
I wasn’t able to reproduce the problem. Are you using the newest version of ProjLib? If so, could you please provide a minimal working example?

**Comment by i-Faye00** [comment]
I am so sorry, the documentclass I used is the Lebhart. I apology for that. 
By the way, running with the pacakges "geometry" or "hyperref" also cause error. 

The mwe follows here:  (the margin is very small, as shown by the page number)

%% Using the class "lebhart"
\documentclass[a4paper,allowbf,11pt]{lebhart}
% \usepackage[a4paper,margin=.75in]{geometry}
% \usepackage[hidelinks]{hyperref}

\usepackage[palatino,amsfashion]{ProjLib}
\usepackage{lipsum}

\begin{document}

\lipsum[1-2]

\end{document}

**Comment by Jinwen-XU** [comment]
Sorry for the late reply. I am currently away from my home country and thus encountered some difficulties regarding internet connection.

You are right. When I wrote the document class "lebhart", I didn't considered supporting font sizes other than the default 10pt. The reason for this is that it is difficult for the icons next to environments such as "remark" to be placed in the same relative position under different font sizes. Therefore, at the time, I thought that maybe it would be a better idea to make the paper size smaller if a larger font size is needed. Of course, these are all negotiable, I can definitely add some support for different font sizes or more page size options in a future version.

Back to the problem of margin, it is because currently I measured the width of the text area using the unit `em`, which changes with the main font size:
```latex
\geometry{
    papersize={8.5in,11in},
    total={47em,66em},
    hmarginratio=1:1,
    vmarginratio=1:1,
    footnotesep=2em plus 2pt minus 2pt,
}
```
For the moment, you can reset the geometry parameters to use other units such as `in` or `mm`.

Regarding the usage of "hyperref" and "geometry" packages, the error happens because these two packages are being used inside the document class "lebhart", thus you cannot call it again using `\usepackage` with different options. However, you can directly write, for example:
```latex
\geometry{
    % Your settings for the page geometry, such as "a4paper, margin=.75in"
}
```
and
```latex
\hypersetup{
    % Your settings for hyperlinks, such as "colorlinks"
}
```

**Comment by Jinwen-XU** [comment]
I should mention that this has been fixed since Update 2021-10-23 (Jinwen-XU/colorist@54d05d266a3636719f522bdf678813cdde774306) of `colorist`.
