### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by robdiaz** [Jinwen-XU/ProjLib#4]
I recently updated my packages and ran into an error

! Package create-theorem Error: The theorem-like environment
(create-theorem)                "definition-lemma" cannot be created, you
(create-theorem)                have to name it before initialization.

when trying to compile

\documentclass{colorbook}
\usepackage{ProjLib}
\UseLanguage{English}

\begin{document}

Hello

\end{document}

**Comment by Jinwen-XU** [comment]
Thank you for pointing this out, and sorry for the inconvenience! It turns out that I forgot to submit the corresponding update of the package `create-theorem` accordingly. I shall upload the new version today and you should be able to receive the update from CTAN by tomorrow.

In the meantime, if you are writing some document today, try adding the following two lines in your document to temporarily resolve the errors (however, please _remember to remove these two lines after you receive the update_):
```latex
\NameTheorem{definition-lemma}{combined={definition;lemma}}
\NameTheorem{lemma-definition}{combined={lemma;definition}}
```

**Comment by robdiaz** [comment]
Hi Jinwen,

My pleasure! I am a fan of your package authoring, so I am happy to have helped. I was in the process of seeing how my course notes would behave under the use of Knitr so I was experimenting myself.

Cheers,

Robert
Fullerton, California

From: Jinwen XU ***@***.***>
Date: Monday, November 11, 2024 at 7:26 PM
To: Jinwen-XU/ProjLib ***@***.***>
Cc: Robert Diaz ***@***.***>, Author ***@***.***>
Subject: Re: [Jinwen-XU/ProjLib] Error after update (Issue #4)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Thank you for pointing this out, and sorry for the inconvenience! It turns out that I forgot to submit the corresponding update of the package create-theorem accordingly. I shall upload the new version today and you should be able to receive the update from CTAN by tomorrow.

In the meantime, if you are writing some document today, try adding the following two lines in your document to temporarily resolve the errors (however, please remember to remove these two lines after you receive the update):

\NameTheorem{definition-lemma}{combined={definition;lemma}}

\NameTheorem{lemma-definition}{combined={lemma;definition}}
